# -*- coding: utf-8 -*-
"""
Time: 2026/1/3 15:32
Author: lcqin111
Version: V1.0
File: layers.py
Description: This script is auto-generated by PyCharm
"""
from typing import Any, Optional, Tuple, Type
import math

import numpy as np
import torch
from torch import Tensor, nn
import torch.nn.functional as F


class Conv1DBlock(nn.Module):
    """Basic 1D convolution block: Conv1d + BN + GELU"""
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.conv = nn.Conv1d(
            in_channels,
            out_channels,
            kernel_size=kernel_size,
            stride=stride,
            padding=padding,
            bias=False
        )
        self.bn = nn.BatchNorm1d(out_channels)
        self.act = nn.GELU() # or nn.ReLU()

    def forward(self, x):
        # x shape: (B, C, L)
        return self.act(self.bn(self.conv(x)))


class ResidualBlock1D(nn.Module):
    """1D residual block: output = input + residual"""

    def __init__(self, channels, kernel_size=3):
        super().__init__()
        # Residual path F(x): Conv -> BN -> Act -> Conv -> BN
        self.conv1 = nn.Conv1d(channels, channels, kernel_size=kernel_size, padding=kernel_size // 2, bias=False)
        self.bn1 = nn.BatchNorm1d(channels)
        self.act = nn.GELU()
        self.conv2 = nn.Conv1d(channels, channels, kernel_size=kernel_size, padding=kernel_size // 2, bias=False)
        self.bn2 = nn.BatchNorm1d(channels)

    def forward(self, x):
        # x shape: (B, C, L)

        # 1. Save original input (for skip connection)
        residual = x

        # 2. Pass through convolution layers
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.act(out)

        out = self.conv2(out)
        out = self.bn2(out)

        # 3. Residual connection: add original input
        # Note: many designs activate after addition, here we activate after addition as well
        out = self.act(out + residual)

        return out


class MultiScaleFeatureFusion(nn.Module):
    def __init__(self, embed_dim, num_layers_to_fuse=4, dropout_prob=0.1):
        super(MultiScaleFeatureFusion, self).__init__()
        self.embed_dim = embed_dim
        self.num_layers = num_layers_to_fuse

        # 1. Create independent Linear layers for each layer
        # Purpose: align feature distributions from different layers
        proj_dim = embed_dim // num_layers_to_fuse
        self.layer_projections = nn.ModuleList([
            nn.Linear(embed_dim, proj_dim) for _ in range(num_layers_to_fuse)
        ])

        # 2. Activation function
        self.activation = nn.GELU()

        # 3. Dropout layer
        self.dropout = nn.Dropout(dropout_prob)

        # 4. Final fusion Linear layer
        # Input dimension is embed_dim * num_layers (due to concat)
        self.final_projection = nn.Linear(proj_dim * num_layers_to_fuse, embed_dim)

    def forward(self, layer_features):
        """
        Input:
            layer_features: List[Tensor], containing num_layers tensors
                           each tensor has shape (B, N, D)
        Output:
            fused_feature: Tensor, shape (B, N, D)
        """
        assert len(layer_features) == self.num_layers, \
            f"Number of input feature layers {len(layer_features)} does not match defined fusion layers {self.num_layers}"

        projected_feats = []

        # Apply Linear -> GELU -> Dropout for each layer's features
        for i, feat in enumerate(layer_features):
            x = self.layer_projections[i](feat)  # (B, N, D)
            x = self.activation(x)  # activate
            x = self.dropout(x)  # regularize
            projected_feats.append(x)

        # Concatenate along feature dimension
        # (B, N, D/4) + (B, N, D/4) + (B, N, D/4) -> (B, N, D)
        fused = torch.cat(projected_feats, dim=-1)

        # Final dimensionality reduction
        output = self.final_projection(fused)  # (B, N, D) -> (B, N, D)

        return output


class MLPBlock(nn.Module):
    def __init__(
        self,
        embedding_dim: int,
        mlp_dim: int,
        act: Type[nn.Module] = nn.GELU,
    ) -> None:
        super().__init__()
        self.lin1 = nn.Linear(embedding_dim, mlp_dim)
        self.lin2 = nn.Linear(mlp_dim, embedding_dim)
        self.act = act()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.lin2(self.act(self.lin1(x)))


# From https://github.com/facebookresearch/detectron2/blob/main/detectron2/layers/batch_norm.py # noqa
# Itself from https://github.com/facebookresearch/ConvNeXt/blob/d1fa8f6fef0a165b27399986cc2bdacc92777e40/models/convnext.py#L119  # noqa
class LayerNorm2d(nn.Module):
    def __init__(self, num_channels: int, eps: float = 1e-6) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(num_channels))
        self.bias = nn.Parameter(torch.zeros(num_channels))
        self.eps = eps

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        u = x.mean(1, keepdim=True)
        s = (x - u).pow(2).mean(1, keepdim=True)
        x = (x - u) / torch.sqrt(s + self.eps)
        x = self.weight[:, None, None] * x + self.bias[:, None, None]
        return x


class TwoWayAttentionBlock(nn.Module):
    def __init__(
        self,
        embedding_dim: int,
        num_heads: int,
        mlp_dim: int = 2048,
        activation: Type[nn.Module] = nn.ReLU,
        attention_downsample_rate: int = 2,
        skip_first_layer_pe: bool = False,
    ) -> None:
        """
        A transformer block with four layers: (1) self-attention of sparse
        inputs, (2) cross attention of sparse inputs to dense inputs, (3) mlp
        block on sparse inputs, and (4) cross attention of dense inputs to sparse
        inputs.

        Arguments:
          embedding_dim (int): the channel dimension of the embeddings
          num_heads (int): the number of heads in the attention layers
          mlp_dim (int): the hidden dimension of the mlp block
          activation (nn.Module): the activation of the mlp block
          skip_first_layer_pe (bool): skip the PE on the first layer
        """
        super().__init__()
        self.self_attn = Attention(embedding_dim, num_heads)
        self.norm1 = nn.LayerNorm(embedding_dim)

        self.cross_attn_token_to_image = Attention(
            embedding_dim, num_heads, downsample_rate=attention_downsample_rate
        )
        self.norm2 = nn.LayerNorm(embedding_dim)

        self.mlp = MLPBlock(embedding_dim, mlp_dim, activation)
        self.norm3 = nn.LayerNorm(embedding_dim)

        self.norm4 = nn.LayerNorm(embedding_dim)
        self.cross_attn_image_to_token = Attention(
            embedding_dim, num_heads, downsample_rate=attention_downsample_rate
        )

        self.skip_first_layer_pe = skip_first_layer_pe

    def forward(
        self, queries: Tensor, keys: Tensor, query_pe: Tensor, key_pe: Tensor
    ) -> Tuple[Tensor, Tensor]:
        # Self attention block
        if self.skip_first_layer_pe:
            queries = self.self_attn(q=queries, k=queries, v=queries)
        else:
            q = queries + query_pe
            attn_out = self.self_attn(q=q, k=q, v=queries)
            queries = queries + attn_out
        queries = self.norm1(queries)

        # Cross attention block, tokens attending to image embedding
        q = queries + query_pe
        k = keys + key_pe
        attn_out = self.cross_attn_token_to_image(q=q, k=k, v=keys)
        queries = queries + attn_out
        queries = self.norm2(queries)

        # MLP block
        mlp_out = self.mlp(queries)
        queries = queries + mlp_out
        queries = self.norm3(queries)

        # Cross attention block, image embedding attending to tokens
        q = queries + query_pe
        k = keys + key_pe
        attn_out = self.cross_attn_image_to_token(q=k, k=q, v=queries)
        keys = keys + attn_out
        keys = self.norm4(keys)

        return queries, keys


class Attention(nn.Module):
    """
    An attention layer that allows for downscaling the size of the embedding
    after projection to queries, keys, and values.
    """

    def __init__(
        self,
        embedding_dim: int,
        num_heads: int,
        downsample_rate: int = 1,
    ) -> None:
        super().__init__()
        self.embedding_dim = embedding_dim
        self.internal_dim = embedding_dim // downsample_rate
        self.num_heads = num_heads
        assert self.internal_dim % num_heads == 0, "num_heads must divide embedding_dim."

        self.q_proj = nn.Linear(embedding_dim, self.internal_dim)
        self.k_proj = nn.Linear(embedding_dim, self.internal_dim)
        self.v_proj = nn.Linear(embedding_dim, self.internal_dim)
        self.out_proj = nn.Linear(self.internal_dim, embedding_dim)

    def _separate_heads(self, x: Tensor, num_heads: int) -> Tensor:
        b, n, c = x.shape
        x = x.reshape(b, n, num_heads, c // num_heads)
        return x.transpose(1, 2)  # B x N_heads x N_tokens x C_per_head

    def _recombine_heads(self, x: Tensor) -> Tensor:
        b, n_heads, n_tokens, c_per_head = x.shape
        x = x.transpose(1, 2)
        return x.reshape(b, n_tokens, n_heads * c_per_head)  # B x N_tokens x C

    def forward(self, q: Tensor, k: Tensor, v: Tensor) -> Tensor:
        # Input projections
        q = self.q_proj(q)
        k = self.k_proj(k)
        v = self.v_proj(v)

        # Separate into heads
        q = self._separate_heads(q, self.num_heads)
        k = self._separate_heads(k, self.num_heads)
        v = self._separate_heads(v, self.num_heads)

        # Attention
        _, _, _, c_per_head = q.shape
        attn = q @ k.permute(0, 1, 3, 2)  # B x N_heads x N_tokens x N_tokens
        attn = attn / math.sqrt(c_per_head)
        attn = torch.softmax(attn, dim=-1)

        # Get output
        out = attn @ v
        out = self._recombine_heads(out)
        out = self.out_proj(out)

        return out


class TwoWayTransformer(nn.Module):
    def __init__(
        self,
        depth: int,
        embedding_dim: int,
        num_heads: int,
        mlp_dim: int,
        activation: Type[nn.Module] = nn.ReLU,
        attention_downsample_rate: int = 2,
    ) -> None:
        """
        A transformer decoder that attends to an input image using
        queries whose positional embedding is supplied.

        Args:
          depth (int): number of layers in the transformer
          embedding_dim (int): the channel dimension for the input embeddings
          num_heads (int): the number of heads for multihead attention. Must
            divide embedding_dim
          mlp_dim (int): the channel dimension internal to the MLP block
          activation (nn.Module): the activation to use in the MLP block
        """
        super().__init__()
        self.depth = depth
        self.embedding_dim = embedding_dim
        self.num_heads = num_heads
        self.mlp_dim = mlp_dim
        self.layers = nn.ModuleList()

        for i in range(depth):
            self.layers.append(
                TwoWayAttentionBlock(
                    embedding_dim=embedding_dim,
                    num_heads=num_heads,
                    mlp_dim=mlp_dim,
                    activation=activation,
                    attention_downsample_rate=attention_downsample_rate,
                    skip_first_layer_pe=(i == 0),
                )
            )

        self.final_attn_token_to_image = Attention(
            embedding_dim, num_heads, downsample_rate=attention_downsample_rate
        )
        self.norm_final_attn = nn.LayerNorm(embedding_dim)

    def forward(
        self,
        image_embedding: Tensor,
        image_pe: Tensor,
        point_embedding: Tensor,
    ) -> Tuple[Tensor, Tensor]:
        """
        Args:
          image_embedding (torch.Tensor): image to attend to. Should be shape
            B x embedding_dim x h x w for any h and w.
          image_pe (torch.Tensor): the positional encoding to add to the image. Must
            have the same shape as image_embedding.
          point_embedding (torch.Tensor): the embedding to add to the query points.
            Must have shape B x N_points x embedding_dim for any N_points.

        Returns:
          torch.Tensor: the processed point_embedding
          torch.Tensor: the processed image_embedding
        """
        # BxCxHxW -> BxHWxC == B x N_image_tokens x C
        # bs, c, h, w = image_embedding.shape
        image_embedding = image_embedding.flatten(2).permute(0, 2, 1)
        image_pe = image_pe.flatten(2).permute(0, 2, 1)

        # Prepare queries
        queries = point_embedding
        keys = image_embedding

        # Apply transformer blocks and final layernorm
        for layer in self.layers:
            queries, keys = layer(
                queries=queries,
                keys=keys,
                query_pe=point_embedding,
                key_pe=image_pe,
            )

        # Apply the final attention layer from the points to the image
        q = queries + point_embedding
        k = keys + image_pe
        attn_out = self.final_attn_token_to_image(q=q, k=k, v=keys)
        queries = queries + attn_out
        queries = self.norm_final_attn(queries)

        return queries, keys


class MLP(nn.Module):
    def __init__(
        self,
        input_dim: int,
        hidden_dim: int,
        output_dim: int,
        num_layers: int,
        sigmoid_output: bool = False,
    ) -> None:
        super().__init__()
        self.num_layers = num_layers
        h = [hidden_dim] * (num_layers - 1)
        self.layers = nn.ModuleList(
            nn.Linear(n, k) for n, k in zip([input_dim] + h, h + [output_dim])
        )
        self.sigmoid_output = sigmoid_output

    def forward(self, x):
        for i, layer in enumerate(self.layers):
            x = F.relu(layer(x)) if i < self.num_layers - 1 else layer(x)
        if self.sigmoid_output:
            x = F.sigmoid(x)
        return x


class PositionEmbeddingRandom(nn.Module):
    """
    Positional encoding using random spatial frequencies.
    """

    def __init__(self, num_pos_feats: int = 64, scale: Optional[float] = None) -> None:
        super().__init__()
        if scale is None or scale <= 0.0:
            scale = 1.0
        self.register_buffer(
            "positional_encoding_gaussian_matrix",
            scale * torch.randn((2, num_pos_feats)),
        )

    def _pe_encoding(self, coords: torch.Tensor) -> torch.Tensor:
        """Positionally encode points that are normalized to [0,1]."""
        # assuming coords are in [0, 1]^2 square and have d_1 x ... x d_n x 2 shape
        coords = 2 * coords - 1
        coords = coords @ self.positional_encoding_gaussian_matrix
        coords = 2 * np.pi * coords
        # outputs d_1 x ... x d_n x C shape
        return torch.cat([torch.sin(coords), torch.cos(coords)], dim=-1)

    def forward(self, size: Tuple[int, int]) -> torch.Tensor:
        """Generate positional encoding for a grid of the specified size."""
        h, w = size
        device: Any = self.positional_encoding_gaussian_matrix.device
        grid = torch.ones((h, w), device=device, dtype=torch.float32)
        y_embed = grid.cumsum(dim=0) - 0.5
        x_embed = grid.cumsum(dim=1) - 0.5
        y_embed = y_embed / h
        x_embed = x_embed / w

        pe = self._pe_encoding(torch.stack([x_embed, y_embed], dim=-1))
        return pe.permute(2, 0, 1)  # C x H x W


class EmotionDecoder(nn.Module):
    def __init__(
            self,
            *,
            transformer_dim: 256,
            transformer: nn.Module,
            activation: Type[nn.Module] = nn.GELU,
    ) -> None:
        super().__init__()
        self.transformer_dim = transformer_dim
        self.transformer = transformer

        self.cls_token = nn.Embedding(1, transformer_dim)
        self.au_token = nn.Embedding(1, transformer_dim)
        self.valence_token = nn.Embedding(1, transformer_dim)
        self.arousal_token = nn.Embedding(1, transformer_dim)
        # self.visibility_token = nn.Embedding(1, transformer_dim)
        # self.age_token = nn.Embedding(1, transformer_dim)
        # self.gender_token = nn.Embedding(1, transformer_dim)
        # self.race_token = nn.Embedding(1, transformer_dim)
        # self.mask_tokens = nn.Embedding(11, transformer_dim)

        # self.output_upscaling = nn.Sequential(
        #     nn.ConvTranspose2d(transformer_dim, transformer_dim // 4, kernel_size=2, stride=2),
        #     LayerNorm2d(transformer_dim // 4),
        #     activation(),
        #     nn.ConvTranspose2d(transformer_dim // 4, transformer_dim // 8, kernel_size=2, stride=2),
        #     activation(),
        # )
        #
        # self.output_hypernetwork_mlps = MLP(
        #     transformer_dim, transformer_dim, transformer_dim // 8, 3
        # )

        self.cls_prediction_head = MLP(
            transformer_dim, transformer_dim, 7, 2
        )
        self.au_prediction_head = MLP(
            transformer_dim, transformer_dim, 11, 2
        )
        self.valence_prediction_head = MLP(
            transformer_dim, transformer_dim, 1, 2
        )
        self.arousal_prediction_head = MLP(
            transformer_dim, transformer_dim, 1, 2
        )
        # self.visibility_prediction_head = MLP(
        #     transformer_dim, transformer_dim, 29, 3
        # )
        # self.age_prediction_head = MLP(
        #     transformer_dim, transformer_dim, 8, 3
        # )
        # self.gender_prediction_head = MLP(
        #     transformer_dim, transformer_dim, 2, 3
        # )
        # self.race_prediction_head = MLP(
        #     transformer_dim, transformer_dim, 5, 3
        # )

    def forward(
            self,
            image_embeddings: torch.Tensor,
            image_pe: torch.Tensor,
    ) -> tuple[Any, Any, Any, Any]:
        output_tokens = torch.cat([self.cls_token.weight, self.au_token.weight,
                                   self.valence_token.weight, self.arousal_token.weight], dim=0)
        tokens = output_tokens.unsqueeze(0).expand(image_embeddings.size(0), -1, -1)

        src = image_embeddings
        pos_src = image_pe.expand(image_embeddings.size(0), -1, -1, -1)
        # b, c, h, w = src.shape

        hs, src = self.transformer(src, pos_src, tokens)

        cls_token_out = hs[:, 0, :]
        au_token_out = hs[:, 1, :]
        valence_token_out = hs[:, 2, :]
        arousal_token_out = hs[:, 3, :]

        cls_output = self.cls_prediction_head(cls_token_out)
        au_output = self.au_prediction_head(au_token_out)
        valence_output = self.valence_prediction_head(valence_token_out)
        arousal_output = self.arousal_prediction_head(arousal_token_out)

        # src = src.transpose(1, 2).view(b, c, h, w)
        # upscaled_embedding = self.output_upscaling(src)
        # hyper_in = self.output_hypernetwork_mlps(mask_token_out)
        # b, c, h, w = upscaled_embedding.shape
        # seg_output = (hyper_in @ upscaled_embedding.view(b, c, h * w)).view(b, -1, h, w)

        return cls_output, au_output, valence_output, arousal_output

